//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelFoxProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelFoxEntities : DbContext
    {
        public TravelFoxEntities()
            : base("name=TravelFoxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Compañia> Compañia { get; set; }
        public virtual DbSet<Conductor> Conductor { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Detalle_Usuario> Detalle_Usuario { get; set; }
        public virtual DbSet<Ruta> Ruta { get; set; }
        public virtual DbSet<Sucursal> Sucursal { get; set; }
        public virtual DbSet<Transporte> Transporte { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
