//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelFoxProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        public int idUsuario { get; set; }
        [DisplayName("Usuario")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Ingrese su usuario")]
        public string username { get; set; }
        [DisplayName("Contraseña")]
        [DataType(DataType.Password)]
        [Required(AllowEmptyStrings =false, ErrorMessage ="Ingrese su contraseña")]
        public string password { get; set; }
        public Nullable<int> idDetUsu { get; set; }
    
        public virtual Detalle_Usuario Detalle_Usuario { get; set; }
    }
}
